python score_events.py -d bdtaunuhad_lite --select_table_name=temp_dstartau_detector_inputs_sigmc --update_table_name=candidate_optimized_events_scores_sigmc
python score_events.py -d bdtaunuhad_lite --select_table_name=temp_dstartau_detector_inputs_data --update_table_name=candidate_optimized_events_scores_data
python score_events.py -d bdtaunuhad_lite --select_table_name=temp_dstartau_detector_inputs_generic --update_table_name=candidate_optimized_events_scores_generic
